# -*- coding: utf-8 -*-
"""disjoinsetsv2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZR4amMMlwl3w-zGmyDqfzOsgNRy8hLxt
"""

inputs = input().split()
n, m = int(inputs[0]), int(inputs[1])
parents, rank, max_r = [i for i in range(n)], [], 0
for r in map(int,input().split()):
    if r > max_r:
        max_r=r
    rank.append(r)
    
for _ in range(m):
    d, s = map(int,input().split())
    d, s = d-1, s-1
    while parents[d] != d:
        d = parents[d]
    while parents[s] != s:
        s = parents[s]
    if s==d: 
        print(max_r)
    else:
        rank[d] += rank[s]
        rank[s] = 0
        parents[s] = d
        max_r =  max(max_r, rank[d])
        print(max_r)