# -*- coding: utf-8 -*-
"""equations_eq_and_noteq.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KYFaewoeRqNI_VCTin0zyTJ0qdH6tAA3
"""

n, e, d = map(int,input().split())
parent = [i for i in range(n)]
for _ in range(e):
    i, j = map(int,input().split())
    parent[j] = parent[i] 

for _ in range(d):
    i, j = map(int,input().split())
    if parent[i] == parent[j]:
        print(0)
        break
else:
    print(1)