# -*- coding: utf-8 -*-
"""gcd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1orpPuTlNcSPD7yEy05jOzAAlivi0ggH5
"""

def gcd0(a,b):
    if a==b:
        return a
    elif a < b:
        return gcd0(a-b,b)
    else: # a < b
        return gcd0(a,b-a)

      
def gcd1(a,b):
    if b == 0:
        return a
    return gcd1(b,a%b)

      
def gcd(a,b):
    return a if b == 0 else gcd(b, a % b)