# -*- coding: utf-8 -*-
"""large_encrease_subseq.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ckmQOOOYRYlQb4AS25RgqO3IPMSqgng4
"""

from sys import stdin

reader = (list(map(int,line.split())) for line in stdin)

n = next(reader)[0]
A = next(reader)
D = [1] * n

for i in range(n):
    for j in range(i):
        if A[i] <= A[j] and D[j] + 1 > D[i]:
            D[i] = D[j] + 1

k = max(D)
print(k)
first = True
result = [0] * k
for i in range(n-1,-1,-1):
    if first:
        if D[i] == k:
            result[-1] = i + 1
            k-=1 
            first = False
    elif D[i] == k and A[result[k]-1] <= A[i]:
        result[k-1] = i + 1
        k -= 1


print(*result)

