# -*- coding: utf-8 -*-
"""Titanic(looking pandas).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i1r3nYTa6Z5fePoKJNIM-cLDAnwrgRw4
"""

import pandas as pd
titanic_data = pd.read_csv('titanic.csv', index_col='PassengerId')

"""Исследуем представленный датафрейм:"""

print(titanic_data.describe(), end="\n\n")
print("Shape: ", titanic_data.shape, end="\n\n")
titanic_data.info()
titanic_data.head()

"""При избавлении от строк с пропущенными значениями (NaN) выбрасывается слишком много строк, и при этом для правильных ответов на поставленные вопросы нам необходимы все данные, поэтому код ниже закомменитируем:"""

#titanic_data = titanic_data.dropna()
#titanic_data.info()

"""Какое количество мужчин и женщин ехало на корабле? В качестве ответа приведите два числа через пробел."""

count_male = titanic_data[titanic_data["Sex"] == "male"]["Sex"].count()
count_female = titanic_data["Sex"].count() - count_male
with open("1.txt", "w") as file:
    file.write(str(count_male) + " " + str(count_female))

"""Какой части пассажиров удалось выжить? Посчитайте долю выживших пассажиров. Ответ приведите в процентах (число в интервале от 0 до 100, знак процента не нужен), округлив до двух знаков."""

survived_perc = round(titanic_data.describe().loc["mean", "Survived"] * 100, 2)
#titanic_data_survived = titanic_data[titanic_data["Survived"]>0]
#survived_perc = round(100 *titanic_data_survived["Survived"].count()/titanic_data["Survived"].count())
with open("2.txt", "w") as file:
    file.write(str(survived_perc))

"""Какую долю пассажиры первого класса составляли среди всех пассажиров? Ответ приведите в процентах (число в интервале от 0 до 100, знак процента не нужен), округлив до двух знаков."""

titanic_data_fcls = titanic_data[titanic_data["Pclass"]==1]
fcls_perc = round(100 * titanic_data_fcls["Pclass"].count()/titanic_data["Pclass"].count(), 2)
with open("3.txt", "w") as file:
    file.write(str(fcls_perc))

"""Какого возраста были пассажиры? Посчитайте среднее и медиану возраста пассажиров. В качестве ответа приведите два числа через пробел."""

mean_age = round(titanic_data.describe().iloc[1, 2], 2)
med_age = titanic_data.describe().loc["50%", "Age"]
with open("4.txt", "w") as file:
    file.write(str(mean_age) + " " + str(med_age))

"""Коррелируют ли число братьев/сестер/супругов с числом родителей/детей? Посчитайте корреляцию Пирсона между признаками SibSp и Parch."""

pirs_corr_relatives = round(titanic_data.corr().loc["SibSp","Parch"], 2)
with open("5.txt", "w") as file:
    file.write(str(pirs_corr_relatives))

"""Какое самое популярное женское имя на корабле? Извлеките из полного имени пассажира (колонка Name) его личное имя (First Name). Попробуйте вручную разобрать несколько значений столбца Name и выработать правило для извлечения имен."""

titanic_data[titanic_data["Sex"] == "female"]["Name"].head(15)

print(count_male, count_female, "\n", survived_perc,"\n", fcls_perc, "\n", mean_age, med_age,  "\n", pirs_corr_relatives)

